### ISSUE TITLE
Idempotence Breaks For WAS 9

### ISSUE THREAD

**Issue by fia5000** [amimof/ansible-websphere#2]
The Idempotency checks break for WAS 9. In WAS 9 ND/BASE, IBM now stipulates to install the JDK alongside the WAS repository through Installation Manager.

so:
`id: com.ibm.websphere.ND.v90, com.ibm.java.jdk.v8` 

The idempotency check in the module can only handle 1 package id at a time and therefore the `imcl listpackages -long` is not parsed correctly, causing the module to install both packages again, even if they are present.

**Comment by ronnicek** [comment]
Hi,

how did you solve it? :)
